# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_coder/design_coder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder || ORIG_REF_NAME==design_coder} -quiet] -quiet

# IP: bd/design_coder/ip/design_coder_processing_system7_0_0/design_coder_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder_processing_system7_0_0 || ORIG_REF_NAME==design_coder_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_coder/ip/design_coder_hammingCoder_ip_0_0/design_coder_hammingCoder_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder_hammingCoder_ip_0_0 || ORIG_REF_NAME==design_coder_hammingCoder_ip_0_0} -quiet] -quiet

# IP: bd/design_coder/ip/design_coder_auto_pc_0/design_coder_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder_auto_pc_0 || ORIG_REF_NAME==design_coder_auto_pc_0} -quiet] -quiet

# IP: bd/design_coder/ip/design_coder_ps7_0_axi_periph_0/design_coder_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_coder_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_coder/ip/design_coder_rst_ps7_0_100M_0/design_coder_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_coder_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_coder_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/design_coder/design_coder_ooc.xdc
